// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementAPI.Models;

#nullable disable

namespace TaskManagementAPI.Migrations
{
    [DbContext(typeof(TaskApplicationDbContext))]
    partial class TaskApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagementAPI.Models.TaskComments", b =>
                {
                    b.Property<int>("TaskCommentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskCommentid"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("task_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("TaskCommentid");

                    b.HasIndex("task_id");

                    b.HasIndex("user_id");

                    b.ToTable("TaskComments");

                    b.HasData(
                        new
                        {
                            TaskCommentid = 1,
                            Comments = "Initial setup done",
                            task_id = 1,
                            user_id = 1
                        },
                        new
                        {
                            TaskCommentid = 2,
                            Comments = "Test cases added",
                            task_id = 2,
                            user_id = 2
                        },
                        new
                        {
                            TaskCommentid = 3,
                            Comments = "Fixed issue #123",
                            task_id = 3,
                            user_id = 2
                        },
                        new
                        {
                            TaskCommentid = 4,
                            Comments = "Deployed successfully",
                            task_id = 4,
                            user_id = 4
                        },
                        new
                        {
                            TaskCommentid = 5,
                            Comments = "Reviewed and approved",
                            task_id = 5,
                            user_id = 5
                        });
                });

            modelBuilder.Entity("TaskManagementAPI.Models.Tasks", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("Assigned_Userid")
                        .HasColumnType("int");

                    b.Property<string>("Taskname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TaskId");

                    b.HasIndex("Assigned_Userid");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Assigned_Userid = 1,
                            Taskname = "Build API"
                        },
                        new
                        {
                            TaskId = 2,
                            Assigned_Userid = 2,
                            Taskname = "Write Tests"
                        },
                        new
                        {
                            TaskId = 3,
                            Assigned_Userid = 3,
                            Taskname = "Fix Bugs"
                        },
                        new
                        {
                            TaskId = 4,
                            Assigned_Userid = 4,
                            Taskname = "Deploy to Server"
                        },
                        new
                        {
                            TaskId = 5,
                            Assigned_Userid = 5,
                            Taskname = "Code Review"
                        });
                });

            modelBuilder.Entity("TaskManagementAPI.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diana"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ethan"
                        });
                });

            modelBuilder.Entity("TaskManagementAPI.Models.TaskComments", b =>
                {
                    b.HasOne("TaskManagementAPI.Models.Tasks", "Tasks")
                        .WithMany("taskcomments")
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagementAPI.Models.Users", "Users")
                        .WithMany("taskcomments")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tasks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskManagementAPI.Models.Tasks", b =>
                {
                    b.HasOne("TaskManagementAPI.Models.Users", "Assignedusers")
                        .WithMany("tasks")
                        .HasForeignKey("Assigned_Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignedusers");
                });

            modelBuilder.Entity("TaskManagementAPI.Models.Tasks", b =>
                {
                    b.Navigation("taskcomments");
                });

            modelBuilder.Entity("TaskManagementAPI.Models.Users", b =>
                {
                    b.Navigation("taskcomments");

                    b.Navigation("tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
